scenario:
  - "vine on top"
start_coordinate:
  - [ 0.0, 0.1 ]
goal_coordinate:
  - [ 0.3, 1.35 ]
number_of_obstacles:
  - 7
obstacles:
  - [ [ 0.4, 0 ], [ 0.7, 0 ], [ 0.7, 2.5 ], [ 0.4, 2.5 ] ]
  - [ [ 0.7, 2.5 ], [ 1.0, 2.2 ], [ 1.5, 2.5 ] ]
  - [ [ 1.5, 2.5 ], [ 1.8, 2.8 ], [ 2.3, 2.5 ] ]
  - [ [ 2.3, 2.5 ], [ 2.6, 2.2 ], [ 3.1, 2.5 ] ]
  - [ [ 2.6, 2.2 ], [ 2.6, 1.4 ], [ 2.3, 1.9 ] ]
  - [ [ 3.1, 2.5 ], [ 3.4, 2.2 ], [ 3.9, 2.5 ] ]
  - [ [ 1.5, 0 ], [ 2.5, 0 ], [ 2.5, 0.27 ], [ 1.5, 0.27 ] ]