scenario:
  - "one leaf tree left side"
start_coordinate:
  - [ 0.0, 0.1 ]
goal_coordinate:
  - [ -1.2, 0.77 ]
number_of_obstacles:
  - 3
obstacles:
  - [ [ 0.4, 0 ], [ 0.7, 0 ], [ 0.7, 2.5 ], [ 0.4, 2.5 ] ]
  - [ [ 0.7, 1.5 ], [ 1.0, 1.2 ], [ 1.5, 1.5 ] ]
  - [ [ 1.5, 0 ], [ 2.5, 0 ], [ 2.5, 0.27 ], [ 1.5, 0.27 ] ]