scenario:
  - "two trees right and left two leaves"
start_coordinate:
  - [ 0.0, 0.1 ]
goal_coordinate:
  - [ -0.0, 1.3 ]
number_of_obstacles:
  - 6
obstacles:
  - [ [ 0.4, 0 ], [ 0.7, 0 ], [ 0.7, 2.5 ], [ 0.4, 2.5 ] ]
  - [ [ 0.7, 1.5 ], [ 1.0, 1.2 ], [ 1.5, 1.5 ] ]
  - [ [ 3.2, 0 ], [ 3.5, 0 ], [ 3.5, 2.8 ], [ 3.2, 2.8 ] ]
  - [ [ 3.2, 2 ], [ 2.9, 2.3 ], [ 2.4, 2 ] ]
  - [ [ 2.4, 2 ], [ 2.1, 1.7 ], [ 1.6, 2 ] ]
  - [ [ 1.5, 0 ], [ 2.5, 0 ], [ 2.5, 0.27 ], [ 1.5, 0.27 ] ]